workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add your environment variable groups here
        - firebase_credentials
      vars:
        PACKAGE_NAME: "com.testapp.simplefirebaseapp"
        # Define other environment variables
      java: 17
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Get Flutter packages
        script: |
          # If using Flutter, uncomment:
          # flutter packages pub get
          echo "Using native Android, no Flutter packages needed"
      
      - name: Build Android APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew assembleDebug
      
      - name: Build Android App Bundle
        script: |
          cd $CM_BUILD_DIR
          ./gradlew bundleRelease
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      # Uncomment to publish to Firebase App Distribution
      # firebase:
      #   firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
      #   android:
      #     app_id: $FIREBASE_APP_ID
      #     groups:
      #       - testers
      
      # Uncomment to publish to Google Play
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true

  android-release-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase_credentials
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.testapp.simplefirebaseapp"
      android_signing:
        - keystore_reference
      java: 17
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Build release AAB
        script: |
          cd $CM_BUILD_DIR
          ./gradlew bundleRelease
    
    artifacts:
      - app/build/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: false
